stages:
  - test
  - deploy

cache:
  key: all
  paths:
  - front/node_modules/
  - back/node_modules/

Test:
  stage: test
  script:
    - cd front
    - npm install

Deploy:
  stage: deploy
  variables:
    DEPLOY_DIR: /home/nico/consensus/dev
  script:
    - whoami
    - echo "Build front"
    - cd front
    - npm install --production
    - npm run build
    - rsync -r ./dist/ $DEPLOY_DIR/front
    - echo "Build back"
    - cd ../back
    - npm install --production
    - pm2 stop consensus-dev
    - rsync -r . $DEPLOY_DIR/back --exclude node_modules
    - pm2 start consensus-dev
  environment:
    name: dev
    url: http://51.38.37.160:8000
  only:
    - master
