stages:
  - test
  - deploy

cache:
  key: all
  paths:
  - ts-front/node_modules/
  - ts-back/node_modules/

Test:
  stage: test
  script:
    - cd ts-front
    - yarn install
    - cd ../ts-back
    - npm install
  only:
    - merge_requests

Deploy:
  stage: deploy
  variables:
    DEPLOY_DIR: /home/nico/consensus/dev
  script:
    - whoami
    - echo "Build front"
    - cd ts-front
    - yarn install --production
    - yarn build
    - rsync -r ./dist/ $DEPLOY_DIR/front
    - echo "Build back"
    - cd ../ts-back
    - npm install --production
    - pm2 stop consensus-dev
    - rsync -r . $DEPLOY_DIR/back --exclude node_modules
    - pm2 start consensus-dev --env production
  environment:
    name: dev
    url: http://51.38.37.160:8000
  only:
    - master
