stages:
  - test
  - deploy

cache:
  key: all
  paths:
  - ts-front/node_modules/
  - ts-front/.yarn
  - ts-back/node_modules/

Test:
  stage: test
  script:
    - whoami
    - node -v
    - cd ts-front
    - yarn install --frozen-lockfile
    - cd ../ts-back
    - npm ci
  only:
    - merge_requests

Deploy:
  stage: deploy
  variables:
    DEPLOY_DIR: /home/nico/consensus/dev
  script:
    - echo "Build front"
    - cd ts-front
    - yarn install --frozen-lockfile
    - yarn build
    - rsync -r ./dist/ $DEPLOY_DIR/front
    - echo "Build back"
    - podman build -t consensus .
  environment:
    name: dev
    url: http://51.38.37.160:8000
  only:
    - master
