stages:
  - test
  - build
  - deploy

Build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - cd ts-front
    - docker build -t registry.gitlab.com/noki/consensus/front .
    - docker push registry.gitlab.com/noki/consensus/front
    - cd ../ts-back
    - docker build -t registry.gitlab.com/noki/consensus/back .
    - docker push registry.gitlab.com/noki/consensus/back
  only:
    - master

Deploy:
  stage: deploy
  variables:
    DEPLOY_DIR: /home/nico/consensus/dev
  script:
    - cd $DEPLOY_DIR
    - docker-compose pull
    - docker-compose up -d --force-recreate
  environment:
    name: dev
    url: http://51.38.37.160:8000
  only:
    - master
