version: '2.0'
services:
  web:
#    image: registry.gitlab.com/noki/consensus/front
    image: consensus-front
    ports:
    - "8001:8080"
    links:
    - back
    environment:
    - ROOT_API=http://localhost:8002/api/v1
  back:
#    image: registry.gitlab.com/noki/consensus/back
    image: consensus-back
    ports:
    - "8002:8000"
